### ISSUE TITLE
Updating resources with path ID parameters also sends those IDs in the POST body

### ISSUE THREAD

**Issue by temiyemi** [pariola/paystack#3]
Sending the `id` field with other post data throws an error from Paystack. Case in point: 
```ts
paystack.customer.update({ id: 'CUS_uvwxyz', first_name: 'John', last_name: 'Doe', phone: '+23412341234' })
  .then(body => console.log(body))
  .catch(err => console.error(err))
```

The `id` parameter is only needed in the path for the endpoint, and not in the post body, but gets sent along anyways, therefore the above code throws a `BAD_FIELD_ERROR` from Paystack.

Introspecting, while parsing data used to invoke the functions, path parameters are not unset from the rest of the data.

**Comment by pariola** [comment]
Ohh, never expected that!. I thought only required fields would be pulled from the POST body.

Thanks again!

**Comment by pariola** [comment]
bumping NPM version!

**Comment by mikey247** [comment]
@temiyemi @pariola Please where do I add the customer id for this request??
