### ISSUE TITLE
transfer_recipient.remove throws error

### ISSUE THREAD

**Issue by seyiogunjuyigbe** [pariola/paystack#9]
Hi,

I tried using the `transfer_recipient.remove` method and it throws an error.
`Error: Method not Allowed! - Resource declaration error`

I checked the paystack docs and the only required params is the recipient_code or id.
I have tried
`paystack.transfer_recipient.remove(recipient_code)`
 `paystack.transfer_recipient.remove({recipient_code})`

Please assist.

Thanks again.

**Comment by pariola** [comment]
Sorry, my bad DELETE request wasn't enabled initially. Pushed fix!

Also, use an object instead

```js
paystack.transfer_recipient.remove({recipient_code})
```

Let me know if you experience any other issues!

**Comment by seyiogunjuyigbe** [comment]
Thank you... it works now!
